Home work2
IgorBurunduk/cardsGame pull request #2
Opened 2022-06-28 20:37 UTC by IgorBurunduk

Add global state variable. Add template-engine with blocks and screens.

2022-06-29 08:14 UTC, mrerberg requested changes

2022-06-29 08:14 UTC, mrerberg commented on js/app.config.js
> +const MESSAGES = {
Почему в константе messages делают levels? Сложности можно вынести в отдельную константу вполне

2022-06-29 10:32 UTC, IgorBurunduk commented on js/app.config.js
> +const MESSAGES = {
Внёс изменения [коммитом](https://github.com/IgorBurunduk/cardsGame/pull/2/commits/2919f1bf7ab29166f4999a783f936b99b26721f6)

2022-06-30 08:04 UTC, mrerberg requested changes

2022-06-30 08:04 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[0]
Object.keys(GAME_LEVELS)[0] -> GAME_LEVELS.easy

2022-06-30 08:04 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[1]
GAME_LEVELS.medium

2022-06-30 10:51 UTC, IgorBurunduk commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[1]
Пардон, а зачем? Я выбранный уровень пушу в window.app.selectedLevel, чтобы потом работать с более понятными данными. А это просто data-аттрибут с именем ключа.

2022-06-30 10:58 UTC, IgorBurunduk commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[1]
Плюс в дальнейшем текстовки могут измениться, например вместо 1,2,3 захочется написать "Легко, Средне, Хард". С такими данными работать будет проблематично

2022-07-01 07:46 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[1]
Да, логично

2022-07-01 07:46 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                    'data-level': Object.keys(GAME_LEVELS)[1]
Протупил

2022-08-27 11:18 UTC, merged