Home work3
IgorBurunduk/cardsGame pull request #3
Opened 2022-07-25 15:33 UTC by IgorBurunduk

**Добавлены:**

1. Линтеры
2. Верстка 2 и 3 экранов с макета без логики
3. Генерация самих карт

2022-07-26 07:33 UTC, mrerberg requested changes

2022-07-26 07:40 UTC, IgorBurunduk commented on js/blocks/cards.js
> +    // eslint-disable-next-line no-undef
Там немного. Линтер ругается на подключаемые функции из других файлов, вроде templateEngine или shuffleArray. Хотя при этом всё работает.

2022-07-26 07:42 UTC, IgorBurunduk commented on js/app.js
> +                // eslint-disable-next-line no-undef
а тут забыл удалить, там было другая функция, подключаемая из другого файла)

2022-07-26 15:25 UTC, mrerberg commented on js/blocks/cards.js
> +    // eslint-disable-next-line no-undef
А ты не пытался выяснить причину? Ты просто взял и отключил линтер в этих местах

2022-07-26 15:27 UTC, mrerberg requested changes

2022-07-26 15:27 UTC, mrerberg commented on js/blocks/cards.js
> +function closeCards(cards) {
Вообще, ты их переворачиваешь, flipCards

2022-07-26 15:27 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                content: GAME_LEVELS.hard.text,
text слишком абстрактное имя ключа. Если честно, я бы не выносил текстовку для выбора сложности в конфигурацию

2022-07-26 16:10 UTC, IgorBurunduk commented on js/blocks/cards.js
> +    // eslint-disable-next-line no-undef
Пытался, но так и не понял почему не видит. Видимо надо делать импорты, а не просто подключать в html. Думаю это как раз при инстале вебпака сделать надо будет, но до того урока ещё не дошел :)

2022-07-26 16:13 UTC, IgorBurunduk commented on js/blocks/gameLevels.js
> +                content: GAME_LEVELS.hard.text,
Текстовки потому и выносил в отдельные текстовки на случай, если захочется написать вместо 1,2,3 понятные "Легко, Нормально, Сложно". Вообще, насколько знаю, подобные вещи всегда рекомендуется выносить за пределы логики/кода. Обсуждали в одном из предыдущих PR :)

2022-07-27 07:41 UTC, mrerberg commented on js/blocks/cards.js
> +    // eslint-disable-next-line no-undef
Да, после вебпака будет все ок

2022-07-27 07:42 UTC, mrerberg commented on js/blocks/gameLevels.js
> +                content: GAME_LEVELS.hard.text,
Да, но я бы это сделал в отдельной переменной, не в gameLevels, хотя спорный момент. На твое усмотрение. Я не вижу смысла выносить именно контентную часть в переменные в данном случае, ее не трудно найти и заменить. Но при этом гибкая настройка тоже может подойти

2022-07-27 07:45 UTC, mrerberg approved these changes

2022-08-27 11:19 UTC, merged